package sbnz.bank.rules;
import facts.Loan
import facts.User
import dtos.LoanRequestDto

query findFittingLoan(Long $id)
     $loan: Loan($id;) and
     LoanRequestDto($loan.getMinimumPaymentDeadline() <= rates, $loan.getMaximumPaymentDeadline() >= rates) and
     (User(age > 70, $loan.getMaximumPaymentDeadline() < 12) or User(age <= 70))
end

rule "Find fitting loan"
    when
        findFittingLoan($id;)
    then
     System.out.println("Found");
end
